//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.jared.android.volley;

import org.jared.android.volley.http.RestClient_;

public final class VolleyApplication_
    extends VolleyApplication
{


    private void init_() {
        restClient = new RestClient_();
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

}
