//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.jared.android.volley;


public final class VolleyApplication_
    extends VolleyApplication
{


    private void init_() {
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

}
