//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.jared.android.volley.ui.fragment;

import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import org.jared.android.volley.R.layout;
import org.jared.android.volley.http.RestClient_;

public final class ClubFragment_
    extends ClubFragment
{

    private View contentView_;
    private Handler handler_ = new Handler();

    private void init_(Bundle savedInstanceState) {
        restClient = new RestClient_();
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.list, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static ClubFragment_.FragmentBuilder_ builder() {
        return new ClubFragment_.FragmentBuilder_();
    }

    @Override
    public void updateClubsFromDB() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ClubFragment_.super.updateClubsFromDB();
                } catch (RuntimeException e) {
                    Log.e("ClubFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void updateClubsFromNetWork() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ClubFragment_.super.updateClubsFromNetWork();
                } catch (RuntimeException e) {
                    Log.e("ClubFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ClubFragment build() {
            ClubFragment_ fragment_ = new ClubFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
