//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.jared.android.volley.ui.fragment;

import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import org.jared.android.volley.R.layout;
import org.jared.android.volley.VolleyApplication;

public final class ContentFragment_
    extends ContentFragment
{

    private View contentView_;
    private Handler handler_ = new Handler();

    private void init_(Bundle savedInstanceState) {
        application = ((VolleyApplication) getActivity().getApplication());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        maj = ((TextView) findViewById(org.jared.android.volley.R.id.maj));
        progressBar = ((ProgressBar) findViewById(org.jared.android.volley.R.id.progressBar));
        listView = ((ListView) findViewById(org.jared.android.volley.R.id.list));
        title = ((TextView) findViewById(org.jared.android.volley.R.id.title));
        afterViews();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.list_layout, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static ContentFragment_.FragmentBuilder_ builder() {
        return new ContentFragment_.FragmentBuilder_();
    }

    @Override
    public void updateFromDB() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ContentFragment_.super.updateFromDB();
                } catch (RuntimeException e) {
                    Log.e("ContentFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void updateFromNetWork() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ContentFragment_.super.updateFromNetWork();
                } catch (RuntimeException e) {
                    Log.e("ContentFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ContentFragment build() {
            ContentFragment_ fragment_ = new ContentFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
