//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.jared.android.volley.ui.fragment;

import java.sql.SQLException;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.j256.ormlite.android.apptools.OpenHelperManager;
import com.j256.ormlite.dao.DaoManager;
import com.j256.ormlite.support.ConnectionSource;
import org.jared.android.volley.R.layout;
import org.jared.android.volley.VolleyApplication;
import org.jared.android.volley.model.Update;
import org.jared.android.volley.repository.VolleyDatabaseHelper;

public final class DefaultFragment_
    extends DefaultFragment
{

    private View contentView_;
    private ConnectionSource connectionSource_;
    private Handler handler_ = new Handler();

    private void init_(Bundle savedInstanceState) {
        application = ((VolleyApplication) getActivity().getApplication());
        connectionSource_ = OpenHelperManager.getHelper(getActivity(), VolleyDatabaseHelper.class).getConnectionSource();
        try {
            updateDao = DaoManager.createDao(connectionSource_, Update.class);
        } catch (SQLException e) {
            Log.e("DefaultFragment_", "Could not create DAO", e);
        }
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        progressBar = ((ProgressBar) findViewById(org.jared.android.volley.R.id.progressBar));
        maj = ((TextView) findViewById(org.jared.android.volley.R.id.maj));
        listView = ((ListView) findViewById(org.jared.android.volley.R.id.list));
        title = ((TextView) findViewById(org.jared.android.volley.R.id.title));
        afterViews();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.list_layout, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static DefaultFragment_.FragmentBuilder_ builder() {
        return new DefaultFragment_.FragmentBuilder_();
    }

    @Override
    public void updateUIAsync() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    DefaultFragment_.super.updateUIAsync();
                } catch (RuntimeException e) {
                    Log.e("DefaultFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void updateFromNetWork() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    DefaultFragment_.super.updateFromNetWork();
                } catch (RuntimeException e) {
                    Log.e("DefaultFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public DefaultFragment build() {
            DefaultFragment_ fragment_ = new DefaultFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
